platform :ios, '8.0'

target 'qiqiaoguo' do
    pod 'SDWebImage'
#    pod 'ZYQAssetPickerController',  '~> 1.0.0'
    pod 'AFNetworking', '~> 3.0'
    pod 'libqrencode', '~> 3.4.2'
    pod 'ReactiveCocoa', '~>2.5'
    pod 'Mantle'
    pod 'UMengAnalytics'
    pod 'MJExtension'
    pod 'AsyncDisplayKit'
    pod 'WebASDKImageManager'
    pod 'Colours'
    pod 'CocoaLumberjack'
    pod 'libextobjc'
    pod 'MagicalRecord'
    pod 'MJRefresh', '3.1.12'
    pod 'IQKeyboardManager'
    pod 'MBProgressHUD'
    pod 'FMDB'
    pod 'Masonry'
    pod 'VTMagic'
end
